# version: "3.8"
services:
  laravel:
    build:
      context: ./laravel-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # volumes:
    #   - ./laravel-api:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=news_aggregator
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - mysql

  react:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # volumes:
    #   - ./react-app:/app
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000/api

  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=news_aggregator
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: